import os
import time

print("Печатает")
time.sleep(1)
text = input("Что случилось? ")
if text == "Меня бросила девушка":
    print("Загрузка.")
    print("Загрузка..")
    time.sleep(1)
    print("Загрузка...")
    print("Загрузка....")
    time.sleep(1)
    print("Загрузка.")
    print("Загрузка..")
    print("Загрузка...")
    time.sleep(1)
    print("Загрузка....")
    time.sleep(1)
    print("Загрузка.")
    print("Загрузка..")
    time.sleep(1)
    print("Загрузка...")
    print("Загрузка....")
    os.system("open \"\" https://store.steampowered.com/app/570/Dota_2/")

else:
    print("Печатает")
    time.sleep(1)
    os.system('clear')
    text2 = input("Ты не дед инсайд, но слушаешь Рейза? ")
    if text2 == "Да":
        print("Загрузка.")
        print("Загрузка..")
        time.sleep(1)
        print("Загрузка...")
        print("Загрузка....")
        time.sleep(1)
        print("Загрузка.")
        print("Загрузка..")
        time.sleep(1)
        print("Загрузка...")
        time.sleep(1)
        print("Загрузка....")
        time.sleep(1)
        os.system("open \"\" https://store.steampowered.com/app/570/Dota_2/")

    else:
        print("Печатает")
        time.sleep(1)
        os.system('clear')
        print("Зачем ты запустил эту программу? Поиграй в доту!")
        time.sleep(2)
        print("Загрузка.")
        print("Загрузка..")
        time.sleep(1)
        print("Загрузка...")
        print("Загрузка....")
        os.system('clear')
        time.sleep(1)
        print("Загрузка.")
        time.sleep(1)
        print("Загрузка..")
        time.sleep(1)
        print("Загрузка...")
        print("Загрузка....")
        time.sleep(1)
        os.system("open \"\" https://store.steampowered.com/app/570/Dota_2/")
